version: '2.1'
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  ftp:
    image: delfer/alpine-ftp-server
#    network_mode: host
    ports:
      - 21:21
      - 21000-21010:21000-21010
    environment:
      - USERS=one|1234|/home/one|10000 two|1234|/home/two|10001
    volumes:
      - ./one:/home/one
      - ./two:/home/two